
export const metadata = {
  title: {
    template: "%s | Technical Agency",
    default: "Technical Agency"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
